Repository CalderaWP/Caldera-Forms, pull requests merged in 2019-03, with the labels that each got.

#3020 Re-create conditions for the Variable pricing example form
  bin/activate-plugin.sh
  composer.json
  composer.lock
  includes/templates/variable-price-example.php
Labels: PR (Patch)

#3037 Load render component using wp.element instead of ReactDom
  classes/render/assets.php
  clients/render/build/index.min.js
  clients/render/build/index.min.js.map
  clients/render/components/RenderComponentViaPortal.js
  clients/render/index.js
Labels: PR (Patch)

#3048 Check if Form exists before render
  classes/core.php
Labels: PR (Patch)

#3050 Check if a valid value is assigned to a cf2 file field before trigger…
  clients/render/fileUploads.js
Labels: PR (Patch)

#3045 Set correct value to html during init and events for Range slider field
  assets/js/field-config.js
Labels: PR (Patch)

#3059 Run version_number with 1.8.2-rc.3 format
  caldera-core.php
  package.json
  readme.txt
Labels: PR (Patch)

#3054 Fix columns width in calendar for date field
  fields/date_picker/css/datepicker.css
Labels: PR (Patch)

#3061 Add wp-data as a dependency for render assets
  classes/render/assets.php
Labels: PR (Patch)

#3052 Caldera Forms 1.8.2
  assets/js/field-config.js
  bin/activate-plugin.sh
  caldera-core.php
  classes/core.php
  classes/render/assets.php
  clients/render/build/index.min.js
  clients/render/build/index.min.js.map
  clients/render/components/RenderComponentViaPortal.js
  clients/render/fileUploads.js
  clients/render/index.js
  composer.json
  composer.lock
  fields/date_picker/css/datepicker.css
  fields/gdpr/field.php
  includes/templates/variable-price-example.php
  package.json
  readme.txt
  vendor/symfony/translation/Resources/bin/translation-status.php
Labels: Release PR

#3018 Add a link from Gutenberg block to Form editor page
  clients/blocks/components/LinkToFormEditor.js
  clients/blocks/index.js
  clients/tests/unit/blocks/components/LinkToFormEditor.test.js
Labels: PR (Patch)

#3074 Check if $file attachment is a string and holds multiple files
  classes/email/filters.php
Labels: PR (Patch)

#3063 Print fields that are disabled by default
  classes/core.php
Labels: Has PR

#3069 prevent using non-object component
  clients/render/build/index.min.js
  clients/render/build/index.min.js.map
  clients/render/index.js
Labels: PR (Patch)

#3086 Implement the Hide label option on cf2 fields
  cf2/Fields/RenderField.php
  clients/render/components/CalderaFormsFieldGroup.js
  clients/render/components/CalderaFormsRender.js
  tests/Unit/RenderFieldTest.php
Labels: PR (Patch)

#3087 create caldera_forms_print_translation_strings_in_footer filter
  classes/render/assets.php
  clients/blocks/build/index.min.js
  clients/privacy/build/index.min.js
  clients/pro/build/index.min.js
  clients/render/build/index.min.js
  package.json
Labels: PR (Patch)

#3102 Changelog for 1.8.3
  caldera-core.php
  package.json
  readme.txt
Labels: PR (Patch)

#3111 Reset correct code used by Translaton file
  classes/render/assets.php
Labels: PR (Patch)

#3110 Correct html button for the Resend email button in entry list
  classes/entry/ui.php
Labels: PR (Patch)

#3120 Disable render client when Elementor/ Beaver Builder is editting
  assets/build/css/caldera-forms-front.min.css
  assets/css/caldera-forms-front.css
  assets/js/caldera-forms-front.js
  assets/js/entry-viewer-2.js
  assets/js/parsley.min.js
  assets/js/vue.js
  caldera-core.php
  classes/render/assets.php
  package.json
  readme.txt
Labels: PR (Patch)

#3126 Don't load the block client in front-end
  classes/render/assets.php
Labels: PR (Patch)

#3092 #3091 - Value of additional CSS class name in Caldera Forms block added to rendering
  ui/blocks/init.php
Labels: PR (Patch)

#3129 Caldera Forms 1.8.4
  assets/build/css/caldera-forms-front.min.css
  assets/css/caldera-forms-front.css
  assets/js/caldera-forms-front.js
  assets/js/entry-viewer-2.js
  assets/js/parsley.min.js
  assets/js/vue.js
  caldera-core.php
  classes/entry/ui.php
  classes/render/assets.php
  package.json
  readme.txt
  ui/blocks/init.php
Labels: Release PR
