Repository CalderaWP/Caldera-Forms, pull requests merged in 2019-02, with the labels that each got.

#2965 Unhide a cf2 field with correct field value set
  clients/render/components/CalderaFormsRender.js
  clients/render/index.js
  clients/tests/unit/render/CalderaFormsRender.test.js
Labels: PR (Patch)

#2966 Enqueue clients/render/build/style.min.css
  Gruntfile.js
  classes/render/assets.php
Labels: PR (Patch)

#2933 Improve file field max size errors and validation
  assets/build/css/caldera-forms-front.min.css
  assets/build/js/caldera-forms-front.min.js
  assets/build/js/frontend-script-init.min.js
  assets/css/caldera-forms-front.css
  assets/js/caldera-forms-front.js
  assets/js/entry-viewer-2.js
  assets/js/parsley.min.js
  assets/js/vue.js
  cf2/Fields/Handlers/FileUpload.php
  cf2/Fields/RenderField.php
  classes/files.php
  classes/render/assets.php
  clients/blocks/build/index.min.js
  clients/blocks/build/index.min.js.map
  clients/privacy/build/index.min.js
  clients/privacy/build/index.min.js.map
  clients/pro/build/index.min.js
  clients/pro/build/index.min.js.map
  clients/render/build/index.min.js
  clients/render/build/index.min.js.map
  clients/render/components/CalderaFormsFieldGroup.js
  clients/render/components/CalderaFormsRender.js
  clients/render/components/Fields/FileInput.js
  clients/render/components/Fields/styles/files-field.scss
  clients/render/fileUploads.js
  clients/render/index.js
  clients/render/util.js
  clients/tests/unit/render/CalderaFormsFieldGroup.test.js
  clients/tests/unit/render/CalderaFormsRender.test.js
  clients/tests/unit/render/Fields/FileInput.test.js
  clients/tests/unit/render/Fields/Mocks/MockFileRenderer.test.js
  clients/tests/unit/render/Fields/Mocks/fileFieldConfigs.js
  clients/tests/unit/render/Fields/__snapshots__/FileInput.test.js.snap
  clients/tests/unit/render/Mocks/mockUtils.js
  clients/tests/unit/render/fileUploads.test.js
  clients/tests/unit/render/util.test.js
  tests/Integration/Caldera_Forms_FilesTest.php
  tests/Integration/Handlers/FileFieldHandlerTest.php
  tests/Unit/Fields/Handlers/FileUpload/FileUploadTest.php
  tests/Unit/RenderFieldTest.php
Labels: in progress

#2973 Make sure cf2 is set before declaring cf2.formIdAttr in render/index.js
  clients/render/index.js
Labels: PR (Patch)

#2971 Prevent ajax-core to trigger errors when multiple CF2 file fields are submitting
  clients/blocks/build/index.min.js
  clients/blocks/build/index.min.js.map
  clients/privacy/build/index.min.js
  clients/privacy/build/index.min.js.map
  clients/pro/build/index.min.js
  clients/pro/build/index.min.js.map
  clients/render/build/index.min.js
  clients/render/build/index.min.js.map
  clients/render/fileUploads.js
  clients/render/index.js
  clients/tests/unit/render/Mocks/mockUtils.js
  clients/tests/unit/render/fileUploads.test.js
Labels: PR (Patch)

#2952 Make CF2 File field look like Advanced FIle Field 1
  clients/blocks/build/index.min.js
  clients/blocks/build/index.min.js.map
  clients/privacy/build/index.min.js
  clients/privacy/build/index.min.js.map
  clients/pro/build/index.min.js
  clients/pro/build/index.min.js.map
  clients/render/build/index.min.js
  clients/render/build/index.min.js.map
  clients/render/components/Fields/FileInput.js
  clients/render/components/Fields/styles/files-field.scss
  clients/render/fileUploads.js
  clients/render/util.js
  clients/tests/unit/render/fileUploads.test.js
Labels: PR (Patch)

#2919 Fix CSV export of checkbox fields
  classes/admin.php
  classes/magic/doer.php
  package-lock.json
  package.json
  vendor/composer/ClassLoader.php
  vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegrationAssertPostConditionsForV7AndPrevious.php
  vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegrationAssertPostConditionsForV8.php
  vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/MockeryTestCaseSetUpForV7AndPrevious.php
  vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/MockeryTestCaseSetUpForV8.php
  vendor/mockery/mockery/tests/Mockery/Generator/StringManipulation/Pass/ClassPassTest.php
  vendor/mockery/mockery/tests/Mockery/MockingStaticMethodsCalledObjectStyleTest.php
Labels: PR (Patch)

#2982 Validate cf2 file fields on page navigation
  .gitignore
  .travis.yml
  assets/build/css/caldera-forms-front.min.css
  assets/build/js/caldera-forms-front.min.js
  assets/build/js/frontend-script-init.min.js
  assets/css/caldera-forms-front.css
  assets/js/caldera-forms-front.js
  assets/js/entry-viewer-2.js
  assets/js/frontend-script-init.js
  assets/js/parsley.min.js
  assets/js/vue.js
  cf2/Fields/RenderField.php
  clients/blocks/build/index.min.js
  clients/blocks/build/index.min.js.map
  clients/privacy/build/index.min.js
  clients/privacy/build/index.min.js.map
  clients/pro/build/index.min.js
  clients/pro/build/index.min.js.map
  clients/render/build/index.min.js
  clients/render/build/index.min.js.map
  clients/render/components/CalderaFormsRender.js
  clients/render/components/Fields/FileInput.js
  clients/render/index.js
  clients/render/util.js
  clients/tests/unit/render/CalderaFormsRender.test.js
  clients/tests/unit/render/Fields/__snapshots__/FileInput.test.js.snap
  clients/tests/unit/render/util.test.js
  composer.json
  composer.lock
  package-lock.json
  package.json
  vendor/autoload.php
  vendor/bin/phpunit
  vendor/bin/phpunit.bat
  vendor/calderawp/caldera-forms-query/Tests/plugins/.gitkeep
  vendor/composer/ClassLoader.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  yarn.lock
Labels: PR (Patch)

#2992 Include clients folders (except tests) in the grunt task for npm run …
  Gruntfile.js
Labels: PR (Patch)

#2997 Look for the fieldValue using the field Id instead of fieldIdAttr
  caldera-core.php
  clients/render/components/CalderaFormsRender.js
Labels: PR (Patch)

#2995 Don't run cf2 fields multi page validation if cf2 or cf2.field is mis…
  assets/js/frontend-script-init.js
  clients/render/index.js
Labels: PR (Patch)

#3001 get cf id correctly during upload of adv file v1 fields
  classes/core.php
  includes/functions.php
Labels: PR (Patch)

#3005 Clear old transients on update
  caldera-core.php
  classes/core.php
  classes/transient.php
  composer.lock
  includes/updater.php
  phpunit.xml.dist
  tests/Integration/Caldera_Forms_TransientTest.php
  tests/Integration/EnvironmentTest.php
  vendor/composer/installed.json
Labels: PR (Patch)

#3007 Fix calculation based on other calculation field value
  assets/js/state/state.js
Labels: PR (Patch)

#3006 tests to prove that scheduling field for delete, causes field to be deleted
  tests/Integration/Caldera_Forms_FilesTest.php
  tests/Integration/Features/ContainerServicesAreLoadedTest.php
  tests/Integration/Handlers/Cf1FileUploaderTest.php
  tests/Integration/RestApi/CreateFileTest.php
  tests/Integration/SubmissionsWithFileFieldsTest.php
  tests/Unit/RenderFieldTest.php
  tests/includes/forms/cf2-file-include.php
  tests/test-api-form-object.php
Labels: PR (Patch)

#3009 Set variable table name for wp_options
  classes/transient.php
Labels: PR (Patch)

#3012 1.8.0 changelog
  readme.txt
Labels: PR (Patch)

#3026 Fix conflicted cypress/tests.json
  bin/install-docker.sh
  cypress/tests.json
Labels: PR (Patch)

#3015 Update .pot file for translation reference
  caldera-core.php
  languages/caldera-forms.pot
  package-lock.json
  package.json
  readme.txt
Labels: PR (Patch)

#3028 Use event object data to set form id for cf2 at cf.ajax.request action
  clients/render/index.js
Labels: PR (Patch)

#3019 PHP 5.6 compat in dependency
  composer.json
Labels: PR (Patch)

#2905 #2904 add 'disabled' attribute for Checkbox, Dropdown, and Autocomplete field types
  fields/checkbox/field.php
  fields/dropdown/field.php
  fields/select2/field/field.php
Labels: PR (Patch)

#2914 #2913 Remove forced 'checked' attribute value for Radio field types
  fields/radio/field.php
Labels: PR (Patch)

#2850 Allow integers as option ID for custom autopopulated checkboxes
  classes/field/util.php
  readme.txt
Labels: PR (Patch)

#3034 Changelog
  caldera-core.php
  package.json
  readme.txt
Labels: PR (Patch)

#3032 Caldera Forms 1.8.1
  assets/build/css/caldera-forms-front.min.css
  assets/css/caldera-forms-front.css
  assets/js/caldera-forms-front.js
  assets/js/entry-viewer-2.js
  assets/js/parsley.min.js
  assets/js/vue.js
  bin/install-docker.sh
  caldera-core.php
  classes/field/util.php
  clients/render/build/index.min.js
  clients/render/index.js
  composer.json
  cypress/tests.json
  fields/checkbox/field.php
  fields/dropdown/field.php
  fields/radio/field.php
  fields/select2/field/field.php
  languages/caldera-forms.pot
  package-lock.json
  package.json
  readme.txt
  vendor/symfony/translation/Loader/schema/dic/xliff-core/xliff-core-1.2-strict.xsd
  vendor/symfony/translation/Loader/schema/dic/xliff-core/xliff-core-2.0.xsd
  vendor/symfony/translation/Loader/schema/dic/xliff-core/xml.xsd
Labels: Release PR
